### ISSUE TITLE
Error report submitted by Flexo

### ISSUE THREAD

**Issue by killje** [killje/XPStorage#12]
```
[01:01:01 ERROR]: Could not pass event PlayerInteractEvent to XPStorage v2.1.5.b631
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [creative.jar:git-Spigot-eadd615-bea5a84]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [creative.jar:git-Spigot-eadd615-bea5a84]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) [creative.jar:git-Spigot-eadd615-bea5a84]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:458) [creative.jar:git-Spigot-eadd615-bea5a84]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [creative.jar:git-Spigot-eadd615-bea5a84]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [creative.jar:git-Spigot-eadd615-bea5a84]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [creative.jar:git-Spigot-eadd615-bea5a84]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [creative.jar:git-Spigot-eadd615-bea5a84]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [creative.jar:git-Spigot-eadd615-bea5a84]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [creative.jar:git-Spigot-eadd615-bea5a84]
```

**Comment by killje** [comment]
```
Caused by: java.lang.ClassCastException: me.killje.xpstorage.xpsign.GroupSign cannot be cast to me.killje.xpstorage.xpsign.AbstractXpSign
        at me.killje.xpstorage.eventListeners.OnPlayerInteract.onPlayerInteract(OnPlayerInteract.java:34) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor888.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        ... 17 more
```

**Comment by killje** [comment]
This seems to be a problem by reloading the server in particular this line of code in "OnPlayerInteract.java"

```java

        Object signObject = event.getClickedBlock()
                .getMetadata("XP_STORAGE_XPSIGN").get(0).value();

        AbstractXpSign xpSign = (AbstractXpSign) signObject;
```

Two ways of solving this:
  - It seems that the metadata is not destroyed correctly. This need to made sure both when disabling and enabling
  - Do not get the sign from the metadata but from some other database

The first one need to be done any way, but the second one could help stability, but might be a bit around the way of doing it
