### ISSUE TITLE
Error report submitted by Flexo

### ISSUE THREAD

**Issue by killje** [killje/XPStorage#13]
```
[XPStorage] Disabling XPStorage v2.1.5.b631
[01:07:37 ERROR]: Error occurred while disabling XPStorage v2.1.5.b631 (Is it up to date?)
java.lang.NullPointerException: null
        at me.killje.xpstorage.xpsign.AbstractXpSign.serialize(AbstractXpSign.java:432) ~[?:?]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:33) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representSequence(BaseRepresenter.java:133) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentList.representData(SafeRepresenter.java:183) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:314) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:306) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:270) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:245) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:38) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:68) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at me.killje.spigotgui.util.clsConfiguration.SaveConfig(clsConfiguration.java:78) ~[?:?]
        at me.killje.xpstorage.xpsign.AbstractXpSign.saveSigns(AbstractXpSign.java:250) ~[?:?]
        at me.killje.xpstorage.XPStorage.onDisable(XPStorage.java:110) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[creative.jar:git-Spigot-eadd615-bea5a84]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [creative.jar:git-Spigot-eadd615-bea5a84]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [creative.jar:git-Spigot-eadd615-bea5a84]
        at me.killje.pluginreload.PluginReload.unloadPlugin(PluginReload.java:169) [PluginReload-2.0.0.jar:?]
        at me.killje.pluginreload.PluginReload$2.onCommand(PluginReload.java:49) [PluginReload-2.0.0.jar:?]
```

**Comment by killje** [comment]
This looks like a reload problem but need more investigation.

What happened is that the player was added to the loaded signs, but had no sign associated. This should only happen if it failed to load
